pr: none

trigger:
  branches:
    include:
      - "*"

pool:
  vmImage: ubuntu-latest

variables:
  - group: docker-settings

steps:
  # Login to DockerHub
  - script: docker login -u $(dockerId) -p $pass
    env:
      pass: $(dockerPassword)
    displayName: Login to DockerHub

  # Build and run tests
  - script: |
      docker pull $(dockerRegistry)/$(dockerImageName):cache-test-dependencies || true
      docker pull $(dockerRegistry)/$(dockerImageName):cache-test || true

      docker-compose --file=docker-compose.test.yml build
    displayName: Build test Docker image
    
  - script: docker-compose --file=docker-compose.test.yml run --rm test
    displayName: Run tests on Docker

  # Clean up
  - script: |
      git reset --hard
      git clean -xdf
    displayName: Clean repository

  # Publish
  - publish: $(System.DefaultWorkingDirectory)
    artifact: repository
    displayName: Publish repository as artifact

  # Build web dependencies
  # - script: |
  #     docker pull $(dockerRegistry)/$(dockerImageName):cache-web-dependencies || true

  #     docker build \
  #       --file=Dockerfile \
  #       --cache-from=$(dockerRegistry)/$(dockerImageName):cache-web-dependencies \
  #       --tag=local/dfe-teachers-payment-service:web-dependencies \
  #       --target=dependencies \
  #       .
  #   displayName: Build web dependencies Docker image using 'cache-web-dependencies' as cache
  #   condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')

  - script: |
      docker build \
        --file=Dockerfile \
        --tag=local/dfe-teachers-payment-service:web-dependencies-infra \
        --target=dependencies \
        .
    displayName: Build web dependencies Docker image without cache

    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  # Build web
  # - script: |
  #     docker pull $(dockerRegistry)/$(dockerImageName):latest || true

  #     docker build \
  #       --file=Dockerfile \
  #       --cache-from=local/dfe-teachers-payment-service:web-dependencies \
  #       --cache-from=$(dockerRegistry)/$(dockerImageName):latest \
  #       --tag=local/dfe-teachers-payment-service:web \
  #       --target=web \
  #       --build-arg GIT_COMMIT_HASH=$(Build.SourceVersion) \
  #       .
  #   displayName: Build web Docker image using 'latest' as cache
  #   condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')

  - script: |
      docker build \
        --file=Dockerfile \
        --cache-from=local/dfe-teachers-payment-service:web-dependencies \
        --tag=local/dfe-teachers-payment-service:web-infra \
        --target=web \
        --build-arg GIT_COMMIT_HASH=$(Build.SourceVersion) \
        .
    displayName: Build web Docker image without cache

    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  # Push test images
  - script: |
      docker tag local/dfe-teachers-payment-service:test-dependencies $(dockerRegistry)/$(dockerImageName):cache-test-dependencies-infra

      docker push $(dockerRegistry)/$(dockerImageName):cache-test-dependencies-infra
    displayName: Push test dependencies Docker image for caching

    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  - script: |
      docker tag local/dfe-teachers-payment-service:test $(dockerRegistry)/$(dockerImageName):cache-test-infra

      docker push $(dockerRegistry)/$(dockerImageName):cache-test-infra
    displayName: Push test Docker image for caching

    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  # Push web images
  - script: |
      docker tag local/dfe-teachers-payment-service:web-dependencies $(dockerRegistry)/$(dockerImageName):cache-web-dependencies-infra

      docker push $(dockerRegistry)/$(dockerImageName):cache-web-dependencies-infra
    displayName: Push web dependencies Docker image for caching

    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  - script: |
      docker tag local/dfe-teachers-payment-service:web $(dockerRegistry)/$(dockerImageName):$(Build.BuildNumber)-infra
      docker tag local/dfe-teachers-payment-service:web $(dockerRegistry)/$(dockerImageName):latest-infra

      docker push $(dockerRegistry)/$(dockerImageName):$(Build.BuildNumber)-infra
      docker push $(dockerRegistry)/$(dockerImageName):latest-infra
    displayName: Push web Docker image
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
