version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 3
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: a11y-dialog
    versions:
    - ">= 7.0.a, < 7.1"
  - dependency-name: accessible-autocomplete
    versions:
    - "> 2.0.1, < 2.1"
  - dependency-name: a11y-dialog
    versions:
    - 5.5.1
    - 5.5.2
    - 6.0.0
    - 6.0.1
    - 6.1.0
    - 6.1.1
