inherit_gem:
  dxw-utils:
    - dxw-rubocop.yml
  rubocop-rails:
    - config/rails.yml

AllCops:
  Exclude:
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'bin/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
