# File: pipeline-templates/build.yaml
# This is a file elsewhere in the repository that represents 
# the build stage of our pipeline 

stages:
- stage: Build
  jobs:
  - job: Build
      
    pool:
      name: Hosted VS2017
      demands:
      - msbuild
      - visualstudio
      - vstest

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

        #####Show Directory Structure on Build
  - powershell: |
     Write-Host "Show all folder content"
     Get-ChildItem -Path $(Agent.WorkFolder)\*.* -Recurse -Force
    errorActionPreference: continue
    displayName: 'PowerShell Script List folder structure'
    continueOnError: true
