pr: none

trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: docker-settings

steps:
  # Login to DockerHub
  - script: docker login -u $(dockerId) -p $pass
    env:
      pass: $(dockerPassword)
    displayName: Login to DockerHub

  - task: Docker@2
    displayName: login into ACR
    inputs:
      containerRegistry: 's118d01contreg'
      command: 'login'

  # Build and run tests
  - script: |
      docker pull $(acrRegistry)/$(dockerImageName):cache-test-dependencies || true
      docker pull $(acrRegistry)/$(dockerImageName):cache-test || true
    displayName: Pull test and test dependencies images 

  - task: DockerCompose@0
    displayName: Build test Docker image  
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'azdo.pipelines.cip.S118D.armfe1ef140-8bef-4043-b5ee-c449e6f951ef'
      azureContainerRegistry: '{"loginServer":"s118d01contreg.azurecr.io", "id" : "/subscriptions/8655985a-2f87-44d7-a541-0be9a8c2779d/resourceGroups/s118d01-contreg/providers/Microsoft.ContainerRegistry/registries/s118d01contreg"}'
      dockerComposeFile: 'docker-compose.test.yml'
      action: 'Run a Docker Compose command'
      dockerComposeCommand: 'build'

  # # Clean up
  - script: |
      git reset --hard
      git clean -xdf
    displayName: Clean repository

  # Publish
  - publish: $(System.DefaultWorkingDirectory)
    artifact: repository
    displayName: Publish repository as artifact

  # # Build web dependencies
  - task: Docker@2
    displayName: Build web dependencies Docker image without cache      
    inputs:
      containerRegistry: 's118d01contreg'
      repository: 'teacher-payments-service'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: 'web-dependencies'
      arguments: '--target=dependencies'
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - task: Docker@2
    displayName: Build web Docker image without cache      
    inputs:
      containerRegistry: 's118d01contreg'
      repository: 'teacher-payments-service'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: 'web'
      arguments: '--cache-from=local/dfe-teachers-payment-service:web-dependencies --target=web --build-arg GIT_COMMIT_HASH=$(Build.SourceVersion)'
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')


  # Push test images
  - script: |
      docker tag $(acrRegistry)/local/dfe-teachers-payment-service:test-dependencies $(acrRegistry)/$(dockerImageName):cache-test-dependencies
    displayName: Tag local test dependencies Docker image for caching
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - task: Docker@2
    displayName: Push test dependencies Docker image for caching
    inputs:
      containerRegistry: 's118d01contreg'
      repository: 'teacher-payments-service'
      command: 'push'
      tags: 'cache-test-dependencies'  
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')


  - script: |
      docker tag $(acrRegistry)/local/dfe-teachers-payment-service:test $(acrRegistry)/$(dockerImageName):cache-test
    displayName: Tag local Docker image for caching
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - task: Docker@2
    displayName: Push test Docker image for caching
    inputs:
      containerRegistry: 's118d01contreg'
      repository: 'teacher-payments-service'
      command: 'push'
      tags: 'cache-test'  
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  # # Push web images
  - script: |
      docker tag $(acrRegistry)/teacher-payments-service:web-dependencies $(acrRegistry)/$(dockerImageName):cache-web-dependencies
    displayName: Tag local web dependencies Docker image for caching
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - task: Docker@2
    displayName: Push web dependencies Docker image for caching
    inputs:
      containerRegistry: 's118d01contreg'
      repository: 'teacher-payments-service'
      command: 'push'
      tags: 'cache-web-dependencies'  
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - script: 
      docker tag $(acrRegistry)/local/teacher-payment-service:web $(acrRegistry)/$(dockerImageName):$(Build.BuildNumber)
    displayName: FAIL Tag local build number Docker image for caching
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - task: Docker@2
    displayName: Push build number Docker image
    inputs:
      containerRegistry: 's118d01contreg'
      repository: 'teacher-payments-service'
      command: 'push'
      tags: $(Build.BuildNumber)  
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - script:
      docker tag $(acrRegistry)/local/teacher-payment-service:web $(acrRegistry)/$(dockerImageName):latest
    displayName: Tag local latest Docker image for caching
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - task: Docker@2
    displayName: Push latest Docker image
    inputs:
      containerRegistry: 's118d01contreg'
      repository: 'teacher-payments-service'
      command: 'push'
      tags: latest  
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master') 