version: "3.7"
services:
  test:
    build:
      context: .
      cache_from:
        - dfedigital/teacher-payments-service:base-${BRANCH:-master}
        - dfedigital/teacher-payments-service:dependencies-${BRANCH:-master}
        - dfedigital/teacher-payments-service:test-${BRANCH:-master}
      target: test
    image: dfedigital/teacher-payments-service:test-${BRANCH:-local}
    entrypoint: bundle exec rake db:prepare default
    depends_on:
      - db
    environment:
      DFE_TEACHERS_PAYMENT_SERVICE_DATABASE_USERNAME: postgres
      DFE_TEACHERS_PAYMENT_SERVICE_DATABASE_PASSWORD: password
      DFE_TEACHERS_PAYMENT_SERVICE_DATABASE_HOST: db
    env_file:
      - .env.test
    tty: true
    stdin_open: true

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

volumes:
  db-data:
