version: "3.7"
services:
  web:
    build:
      context: .
      target: test
      args:
        RAILS_ENV: test
    image: local/dfe-teachers-payment-service:test
    depends_on:
      - db
    environment:
      DFE_TEACHERS_PAYMENT_SERVICE_DATABASE_USERNAME: postgres
      DFE_TEACHERS_PAYMENT_SERVICE_DATABASE_HOST: db
    env_file:
      - .env.test
    tty: true
    stdin_open: true
    command: bundle exec spring server

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
