---
:shared:
  :claims:
    - first_name
    - middle_name
    - surname
    - date_of_birth
    - address_line_1
    - address_line_2
    - address_line_3
    - address_line_4
    - postcode
    - national_insurance_number
    - email_address
    - payroll_gender
    - practitioner_email_address
    - provider_contact_name
    - onelogin_uid
    - onelogin_idv_return_codes
  :dfe_sign_in_users:
    - given_name
    - family_name
    - email
  :levelling_up_premium_payments_eligibilities:
    - teacher_reference_number
  :targeted_retention_incentive_payments_eligibilities:
    - teacher_reference_number
  :early_career_payments_eligibilities:
    - teacher_reference_number
  :student_loans_eligibilities:
    - teacher_reference_number
  :further_education_payments_eligibilities:
    - teacher_reference_number
    - claimant_date_of_birth
    - claimant_postcode
    - claimant_national_insurance_number
    - provider_verification_claimant_date_of_birth
    - provider_verification_claimant_email
    - provider_verification_claimant_national_insurance_number
    - provider_verification_claimant_postcode
    - work_email
  :early_years_payment_eligibilities:
    - provider_email_address
    - practitioner_first_name
    - practitioner_surname
    - alternative_idv_claimant_date_of_birth
    - alternative_idv_claimant_postcode
    - alternative_idv_claimant_national_insurance_number
    - alternative_idv_claimant_email
  :early_years_teachers_financial_incentive_payments_eligibilities:
    - trs_data
    - teacher_auth_teacher_reference_number
    - teacher_auth_email
    - teacher_auth_verified_name
    - teacher_auth_verified_date_of_birth
    - teacher_auth_one_login_uid
  :school_workforce_censuses:
    - teacher_reference_number
  :teachers_pensions_service:
    - teacher_reference_number
    - nino
    - gender_digit
  :eligible_fe_providers:
    - primary_key_contact_email_address
  :reminders:
    - full_name
    - email_address
  :active_storage_blobs:
    - filename
  :feedbacks:
    - comment # string, optional comment left by claimant
    - email_address # string, claimant email address if user chose to participate in future user research
    - occupation # string, claimant occupation if user chose to participate in future user research
