---
shared:
  :claims:
  - first_name
  - middle_name
  - surname
  - date_of_birth
  - date_of_birth_day
  - date_of_birth_month
  - date_of_birth_year
  - address_line_1
  - address_line_2
  - address_line_3
  - address_line_4
  - postcode
  - national_insurance_number
  - bank_sort_code
  - bank_account_number
  - building_society_roll_number
  - banking_name
  - mobile_number
  - teacher_reference_number
  - email_address
  - payroll_gender
  - one_time_password
  - hmrc_bank_validation_responses
  :reminders:
  - full_name
  - email_address
  - one_time_password
  :claim_decisions:
  - trn
  - claimant_age
  - claimant_gender
  :school_workforce_censuses:
  - teacher_reference_number
  :teachers_pensions_service:
  - teacher_reference_number
  - gender_digit
  :dfe_sign_in_users:
  - given_name
  - family_name
  - email
