---
shared:
  :journey_configurations:
    - routing_name
    - open_for_submissions
    - availability_message
    - created_at
    - updated_at
    - current_academic_year
    - teacher_id_enabled
  :reminders:
    - id
    - created_at
    - updated_at
    - email_verified
    - email_sent_at
    - itt_academic_year
    - itt_subject
    - sent_one_time_password_at
    - journey_class
    - deleted_at
  :tasks:
    - id
    - name
    - claim_id
    - created_by_id
    - created_at
    - updated_at
    - passed
    - manual
    - claim_verifier_match
    - reason
  :amendments:
    - id
    - claim_id
    - notes
    - claim_changes
    - dfe_sign_in_users_id
    - created_by_id
    - created_at
    - updated_at
    - personal_data_removed_at
  :claims:
    - id
    - created_at
    - updated_at
    - submitted_at
    - reference
    - has_student_loan
    - student_loan_country
    - student_loan_courses
    - student_loan_start_date
    - student_loan_plan
    - govuk_verify_fields
    - eligibility_type
    - eligibility_id
    - personal_data_removed_at
    - academic_year
    - bank_or_building_society
    - provide_mobile_number
    - postgraduate_masters_loan
    - postgraduate_doctoral_loan
    - email_verified
    - has_masters_doctoral_loan
    - mobile_verified
    - assigned_to_id
    - policy_options_provided
    - sent_one_time_password_at
    - held
    - hmrc_bank_validation_succeeded
    - logged_in_with_tid
    - qa_required
    - qa_completed_at
    - details_check
    - email_address_check
    - mobile_check
    - qualifications_details_check
    - submitted_using_slc_data
    - journeys_session_id
    - identity_confirmed_with_onelogin
    - logged_in_with_onelogin
    - onelogin_auth_at
    - onelogin_idv_at
    - onelogin_uid
    - started_at
    - verified_at
    - onelogin_idv_return_codes
    - policy
  :decisions:
    - id
    - claim_id
    - created_at
    - updated_at
    - notes
    - created_by_id
    - undone
    - rejected_reasons
    - approved
  :local_authorities:
    - id
    - code
    - name
  :local_authority_districts:
    - id
    - name
    - code
  :notes:
    - id
    - body
    - claim_id
    - created_by_id
    - created_at
    - updated_at
    - important
    - label
  :payments:
    - id
    - payroll_run_id
    - award_amount
    - created_at
    - updated_at
    - payroll_reference
    - gross_value
    - national_insurance
    - employers_national_insurance
    - student_loan_repayment
    - tax
    - net_pay
    - gross_pay
    - postgraduate_loan_repayment
    - confirmation_id
    - scheduled_payment_date
  :payment_confirmations:
    - id
    - payroll_run_id
    - created_by_id
    - created_at
    - updated_at
  :payroll_runs:
    - id
    - created_at
    - updated_at
    - downloaded_at
    - created_by_id
    - downloaded_by_id
    - scheduled_payment_date
    - confirmation_report_uploaded_by_id
    - status
  :student_loans_eligibilities:
    - id
    - created_at
    - updated_at
    - qts_award_year
    - claim_school_id
    - current_school_id
    - employment_status
    - biology_taught
    - chemistry_taught
    - computing_taught
    - languages_taught
    - physics_taught
    - taught_eligible_subjects
    - student_loan_repayment_amount
    - had_leadership_position
    - mostly_performed_leadership_duties
    - claim_school_somewhere_else
    - teacher_reference_number
  :early_career_payments_eligibilities:
    - id
    - nqt_in_academic_year_after_itt
    - created_at
    - updated_at
    - employed_as_supply_teacher
    - qualification
    - has_entire_term_contract
    - employed_directly
    - subject_to_disciplinary_action
    - subject_to_formal_performance_action
    - eligible_itt_subject
    - teaching_subject_now
    - itt_academic_year
    - current_school_id
    - award_amount
    - induction_completed
    - school_somewhere_else
    - teacher_reference_number
  :targeted_retention_incentive_payments_eligibilities:
    - id
    - created_at
    - updated_at
    - nqt_in_academic_year_after_itt
    - employed_as_supply_teacher
    - qualification
    - has_entire_term_contract
    - employed_directly
    - subject_to_disciplinary_action
    - subject_to_formal_performance_action
    - eligible_itt_subject
    - teaching_subject_now
    - itt_academic_year
    - current_school_id
    - award_amount
    - eligible_degree_subject
    - induction_completed
    - school_somewhere_else
    - teacher_reference_number
  :international_relocation_payments_eligibilities:
    - id
    - created_at
    - updated_at
    - application_route
    - state_funded_secondary_school
    - one_year
    - start_date
    - subject
    - visa_type
    - date_of_entry
    - nationality
    - current_school_id
    - award_amount
  :schools:
    - id
    - urn
    - name
    - street
    - locality
    - town
    - county
    - postcode
    - phase
    - school_type_group
    - school_type
    - local_authority_id
    - created_at
    - updated_at
    - local_authority_district_id
    - close_date
    - establishment_number
    - statutory_high_age
    - phone_number
    - open_date
    - ukprn
  :support_tickets:
    - id
    - url
    - claim_id
    - created_by_id
    - created_at
    - updated_at
  :dfe_sign_in_users:
    - id
    - dfe_sign_in_id
    - organisation_name
    - created_at
    - updated_at
    - role_codes
    - deleted_at
  :targeted_retention_incentive_payments_awards:
    - id
    - academic_year
    - school_urn
    - award_amount
    - created_at
    - updated_at
  :claim_payments:
    - id
    - claim_id
    - payment_id
    - created_at
    - updated_at
  :topups:
    - id
    - claim_id
    - award_amount
    - payment_id
    - dfe_sign_in_users_id
    - created_by_id
    - created_at
    - updated_at
  :journeys_sessions:
    - id
    - journey
    - created_at
    - updated_at
  :further_education_payments_eligibilities:
    - id
    - created_at
    - updated_at
    - award_amount
    - teaching_responsibilities
    - provision_search
    - possible_school_id
    - school_id
    - contract_type
    - fixed_term_full_year
    - taught_at_least_one_term
    - teaching_hours_per_week
    - teaching_hours_per_week_next_term
    - further_education_teaching_start_year
    - subjects_taught
    - building_construction_courses
    - chemistry_courses
    - computing_courses
    - early_years_courses
    - engineering_manufacturing_courses
    - maths_courses
    - physics_courses
    - hours_teaching_eligible_subjects
    - teaching_qualification
    - subject_to_formal_performance_action
    - subject_to_disciplinary_action
    - half_teaching_hours
    - flagged_as_duplicate
    - provider_verification_email_last_sent_at
    - provider_verification_chase_email_last_sent_at
    - teacher_reference_number
    - provider_verification_email_count
    - claimant_identity_verified_at
    - valid_passport
  :eligible_ey_providers:
    - id
    - nursery_name
    - urn
    - local_authority_id
    - nursery_address
    - created_at
    - updated_at
  :eligible_fe_providers:
    - id
    - ukprn
    - academic_year
    - max_award_amount
    - lower_award_amount
    - created_at
    - updated_at
  :early_years_payment_eligibilities:
    - id
    - nursery_urn
    - start_date
    - child_facing_confirmation_given
    - returning_within_6_months
    - returner_worked_with_children
    - returner_contract_type
    - award_amount
    - created_at
    - updated_at
    - provider_claim_submitted_at
    - practitioner_claim_started_at
  :school_workforce_censuses:
    - id
    - teacher_reference_number
    - school_urn
    - totfte
    - contract_agreement_type
    - subject_description_sfr
    - general_subject_code
    - hours_taught
    - created_at
    - updated_at
  :teachers_pensions_service:
    - id
    - teacher_reference_number
    - start_date
    - end_date
    - la_urn
    - school_urn
    - employer_id
    - nino
    - created_at
    - updated_at
    - gender_digit
  :stats:
    - id
    - one_login_return_code
    - created_at
    - updated_at
    - type
