---
shared:
  :policy_configurations:
  - id
  - open_for_submissions
  - availability_message
  - created_at
  - updated_at
  - current_academic_year
  - policy_types
  :reminders:
  - id
  - full_name
  - email_address
  - created_at
  - updated_at
  - email_verified
  - email_sent_at
  - itt_academic_year
  - itt_subject
  - one_time_password
  - one_time_password_category
  - sent_one_time_password_at
  :tasks:
  - id
  - name
  - claim_id
  - created_by_id
  - created_at
  - updated_at
  - passed
  - manual
  - claim_verifier_match
  :amendments:
  - id
  - claim_id
  - notes
  - claim_changes
  - dfe_sign_in_users_id
  - created_by_id
  - created_at
  - updated_at
  - personal_data_removed_at
  :claims:
  - id
  - created_at
  - updated_at
  - address_line_1
  - address_line_2
  - address_line_3
  - address_line_4
  - postcode
  - date_of_birth
  - teacher_reference_number
  - national_insurance_number
  - email_address
  - bank_sort_code
  - bank_account_number
  - submitted_at
  - reference
  - has_student_loan
  - student_loan_country
  - student_loan_courses
  - student_loan_start_date
  - student_loan_plan
  - payroll_gender
  - govuk_verify_fields
  - eligibility_type
  - eligibility_id
  - first_name
  - middle_name
  - surname
  - banking_name
  - building_society_roll_number
  - remove_column_payment_id
  - personal_data_removed_at
  - academic_year
  - bank_or_building_society
  - provide_mobile_number
  - mobile_number
  - postgraduate_masters_loan
  - postgraduate_doctoral_loan
  - email_verified
  - has_masters_doctoral_loan
  - mobile_verified
  - assigned_to_id
  - policy_options_provided
  - one_time_password
  - one_time_password_category
  - sent_one_time_password_at
  - date_of_birth_day
  - date_of_birth_month
  - date_of_birth_year
  - held
  - hmrc_bank_validation_succeeded
  - hmrc_bank_validation_responses
  - logged_in_with_tid
  :decisions:
  - id
  - result
  - claim_id
  - created_at
  - updated_at
  - notes
  - created_by_id
  - undone
  - rejected_reasons
  :local_authorities:
  - id
  - code
  - name
  :local_authority_districts:
  - id
  - name
  - code
  :notes:
  - id
  - body
  - claim_id
  - created_by_id
  - created_at
  - updated_at
  - important
  :payments:
  - id
  - payroll_run_id
  - award_amount
  - created_at
  - updated_at
  - payroll_reference
  - gross_value
  - national_insurance
  - employers_national_insurance
  - student_loan_repayment
  - tax
  - net_pay
  - gross_pay
  - postgraduate_loan_repayment
  - confirmation_id
  - scheduled_payment_date
  :payment_confirmations:
  - id
  - payroll_run_id
  - created_by_id
  - created_at
  - updated_at
  :payroll_runs:
  - id
  - created_at
  - updated_at
  - downloaded_at
  - created_by_id
  - downloaded_by_id
  - scheduled_payment_date
  - confirmation_report_uploaded_by_id
  :student_loans_eligibilities:
  - id
  - created_at
  - updated_at
  - qts_award_year
  - claim_school_id
  - current_school_id
  - employment_status
  - biology_taught
  - chemistry_taught
  - computing_taught
  - languages_taught
  - physics_taught
  - taught_eligible_subjects
  - student_loan_repayment_amount
  - had_leadership_position
  - mostly_performed_leadership_duties
  :maths_and_physics_eligibilities:
  - id
  - teaching_maths_or_physics
  - created_at
  - updated_at
  - current_school_id
  - has_uk_maths_or_physics_degree
  - qts_award_year
  - employed_as_supply_teacher
  - has_entire_term_contract
  - employed_directly
  - subject_to_disciplinary_action
  - subject_to_formal_performance_action
  - initial_teacher_training_subject
  - initial_teacher_training_subject_specialism
  :early_career_payments_eligibilities:
  - id
  - nqt_in_academic_year_after_itt
  - created_at
  - updated_at
  - employed_as_supply_teacher
  - qualification
  - has_entire_term_contract
  - employed_directly
  - subject_to_disciplinary_action
  - subject_to_formal_performance_action
  - eligible_itt_subject
  - teaching_subject_now
  - itt_academic_year
  - current_school_id
  - award_amount
  :levelling_up_premium_payments_eligibilities:
  - id
  - created_at
  - updated_at
  - nqt_in_academic_year_after_itt
  - employed_as_supply_teacher
  - qualification
  - has_entire_term_contract
  - employed_directly
  - subject_to_disciplinary_action
  - subject_to_formal_performance_action
  - eligible_itt_subject
  - teaching_subject_now
  - itt_academic_year
  - current_school_id
  - award_amount
  - eligible_degree_subject
  :schools:
  - id
  - urn
  - name
  - street
  - locality
  - town
  - county
  - postcode
  - phase
  - school_type_group
  - school_type
  - local_authority_id
  - created_at
  - updated_at
  - local_authority_district_id
  - close_date
  - establishment_number
  - statutory_high_age
  - phone_number
  - open_date
  :support_tickets:
  - id
  - url
  - claim_id
  - created_by_id
  - created_at
  - updated_at
  :teachers_pensions_service:
  - id
  - teacher_reference_number
  - start_date
  - end_date
  - la_urn
  - school_urn
  - created_at
  - updated_at
  - gender_digit
  :dfe_sign_in_users:
  - id
  - dfe_sign_in_id
  - given_name
  - family_name
  - email
  - organisation_name
  - created_at
  - updated_at
  - role_codes
  - deleted_at
  :levelling_up_premium_payments_awards:
  - id
  - academic_year
  - school_urn
  - award_amount
  - created_at
  - updated_at
  :claim_payments:
  - id
  - claim_id
  - payment_id
  - created_at
  - updated_at
  :topups:
  - id
  - claim_id
  - award_amount
  - payment_id
  - dfe_sign_in_users_id
  - created_by_id
  - created_at
  - updated_at
