---
:shared:
  :claims:
    - onelogin_uid
    - first_name
    - middle_name
    - surname
    - date_of_birth
  :levelling_up_premium_payments_eligibilities:
    - teacher_reference_number
  :early_career_payments_eligibilities:
    - teacher_reference_number
  :student_loans_eligibilities:
    - teacher_reference_number
  :further_education_payments_eligibilities:
    - teacher_reference_number
  :school_workforce_censuses:
    - teacher_reference_number
  :teachers_pensions_service:
    - teacher_reference_number
    - nino
    - gender_digit
