steps:
  - script: docker login -u $(dockerId) -p $pass
    env:
      pass: $(dockerPassword)
    displayName: Login to DockerHub

  - script: |
      docker version
      docker buildx version
    displayName: Print docker version

  - script: |
      BRANCH_FULL=$(Build.SourceBranch)
      BRANCH=${BRANCH_FULL##*/}
      echo "##vso[task.setvariable variable=BRANCH;]${BRANCH}"
    condition: eq(variables['System.PullRequest.PullRequestNumber'], '')
    displayName: Set short branch name (not pull request)

  - script: |
      BRANCH_FULL=$(System.PullRequest.SourceBranch)
      BRANCH=${BRANCH_FULL##*/}
      echo "##vso[task.setvariable variable=BRANCH;]${BRANCH}"
    condition: ne(variables['System.PullRequest.PullRequestNumber'], '')
    displayName: Set short branch name (pull request)

  - script: |
      docker buildx create --use --name docker-container
      docker buildx inspect --bootstrap --builder docker-container
    displayName: Create buildx driver

  - script: |
      docker buildx build --target base --load \
        -t dfedigital/teacher-payments-service:base-$(BRANCH) \
        --cache-from dfedigital/teacher-payments-service:base-$(BRANCH) \
        --cache-to type=inline \
        .
    displayName: Build base image

  - script: |
      docker buildx build --target dependencies --load \
        -t dfedigital/teacher-payments-service:dependencies-$(BRANCH) \
        --cache-from dfedigital/teacher-payments-service:base-$(BRANCH) \
        --cache-from dfedigital/teacher-payments-service:dependencies-$(BRANCH) \
        --cache-to type=inline \
        .
    displayName: Build dependencies image

  - script: |
      docker buildx build --target web --load \
        -t dfedigital/teacher-payments-service:$(Build.BuildNumber) \
        -t dfedigital/teacher-payments-service:web-$(BRANCH) \
        -t dfedigital/teacher-payments-service:web-$(Build.SourceVersion) \
        -t dfedigital/teacher-payments-service:web-$(COMMIT_ID) \
        --cache-from dfedigital/teacher-payments-service:base-$(BRANCH) \
        --cache-from dfedigital/teacher-payments-service:dependencies-$(BRANCH) \
        --cache-from dfedigital/teacher-payments-service:web-$(BRANCH) \
        --cache-to type=inline \
        .
    displayName: Build web image

  - task: Docker@2
    displayName: Push base image
    inputs:
      command: push
      repository: docker.io/dfedigital/teacher-payments-service
      tags: base-$(BRANCH)
    env:
      DOCKER_BUILDKIT: 1

  - task: Docker@2
    displayName: Push dependencies image
    inputs:
      command: push
      repository: docker.io/dfedigital/teacher-payments-service
      tags: dependencies-$(BRANCH)
    env:
      DOCKER_BUILDKIT: 1

  - task: Docker@2
    displayName: Push web image
    inputs:
      command: push
      repository: docker.io/dfedigital/teacher-payments-service
      tags: |
        $(Build.BuildNumber)
        web-$(BRANCH)
        web-$(Build.SourceVersion)
        web-$(COMMIT_ID)
    env:
      DOCKER_BUILDKIT: 1

  - task: Docker@2
    displayName: Push test image
    inputs:
      command: push
      repository: docker.io/dfedigital/teacher-payments-service
      tags: test-$(BRANCH)
    env:
      DOCKER_BUILDKIT: 1
