---
BYPASS_DFE_SIGN_IN: true
BYPASS_ONELOGIN_SIGN_IN: true
ONELOGIN_DID_URL: https://identity.integration.account.gov.uk/.well-known/did.json

DFE_SIGN_IN_API_CLIENT_ID: teacherpayments
DFE_SIGN_IN_API_ENDPOINT: https://pp-api.signin.education.gov.uk
DFE_SIGN_IN_IDENTIFIER: teacherpayments
DFE_SIGN_IN_ISSUER: https://pp-oidc.signin.education.gov.uk:443

DQT_API_URL: https://preprod.teacher-qualifications-api.education.gov.uk/v1
DQT_BASE_URL: https://test-api-customerengagement.platform.education.gov.uk/dqt-crm/v1/

HMRC_API_BASE_URL: https://test-api.service.hmrc.gov.uk
HMRC_API_BANK_VALIDATION_ENABLED: true

ORDNANCE_SURVEY_API_BASE_URL: https://api.os.uk

SUPPRESS_DFE_ANALYTICS_INIT: true

TID_SIGN_IN_API_ENDPOINT: https://preprod.teaching-identity.education.gov.uk:433
TID_SIGN_IN_CLIENT_ID: claim
TID_SIGN_IN_ISSUER: https://preprod.teaching-identity.education.gov.uk/
TID_BASE_URL: https://claim-additional-payments-for-teaching-review-*.test.teacherservices.cloud/targeted-retention-incentive-payments/claim

GOVUK_APP_DOMAIN: ""
GOVUK_WEBSITE_ROOT: ""
