---
DFE_SIGN_IN_API_CLIENT_ID: teacherpayments # TODO: move to keyvault
DFE_SIGN_IN_API_SECRET: secret # TODO: move to keyvault
DFE_SIGN_IN_API_ENDPOINT: https://example.com

DQT_API_URL: https://teacher-qualifications-api.education.gov.uk/
DQT_API_KEY: 1a2b3c4d5e6f7g8h9i0 # TODO: move to keyvault

DQT_BEARER_BASE_URL: https://login.microsoftonline.com/123456/oauth2/v2.0/token
DQT_BEARER_GRANT_TYPE: client_credentials
DQT_BEARER_SCOPE: https://test.dynamics.com/.default
DQT_BEARER_CLIENT_ID: 1234 # TODO: move to keyvault
DQT_BEARER_CLIENT_SECRET: 5678 # TODO: move to keyvault
DQT_BASE_URL: https://test-api-customerengagement.platform.education.gov.uk/dqt-crm/v1/
DQT_SUBSCRIPTION_KEY: 09876432 # TODO: move to keyvault

ADMIN_ALLOWED_IPS: ::1,127.0.0.1

ENVIRONMENT_NAME: review

ORDNANCE_SURVEY_API_BASE_URL: https://api.os.uk
ORDNANCE_SURVEY_CLIENT_PARAMS: '{ "key": "api-key-value" }'

RUN_FLAKY_SPECS: true
RUN_JS_SPECS: true
RUN_SLOW_SPECS: true

HMRC_API_BASE_URL: https://test-api.service.hmrc.gov.uk
HMRC_API_BANK_VALIDATION_ENABLED: false
HMRC_API_CLIENT_ID: test # TODO: move to keyvault
HMRC_API_CLIENT_SECRET: test # TODO: move to keyvault

TID_SIGN_IN_ISSUER: https://preprod.teaching-identity.education.gov.uk/
TID_SIGN_IN_API_ENDPOINT: https://preprod.teaching-identity.education.gov.uk:433
TID_SIGN_IN_CLIENT_ID: claim # TODO: move to keyvault
