name: Restore Database from Azure Storage
concurrency: build_and_deploy_main

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: Set to true to restore nightly backup to production
        required: true
        default: 'false'
        type: choice
        options:
        - 'false'
        - 'true'
      backup-file:
        description: Name of the backup file in Azure storage. e.g. capt_prod_2024-07-15.sql.gz. The default value is today's backup.
        type: string

jobs:
  restore:
    name: Restore AKS Database (production)
    if: inputs.confirm == 'true'
    runs-on: ubuntu-latest
    environment: production-aks

    steps:
      - name: Set backup file
        run: |
          if [ "${{ inputs.backup-file }}" != "" ]; then
            BACKUP_FILE=${{ inputs.backup-file }}
          else
            BACKUP_FILE=capt_prod_$(date +"%F").sql.gz
          fi
          echo "BACKUP_FILE=$BACKUP_FILE" >> $GITHUB_ENV

      - name: Restore postgres
        uses: DFE-Digital/github-actions/restore-postgres-backup@master
        with:
          storage-account: s189p01captdbbkppdsa
          resource-group: s189p01-capt-pd-rg
          app-name: claim-additional-payments-for-teaching-production-web
          cluster: production
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          backup-file: ${{ env.BACKUP_FILE }}
