name: Delete review app

on:
  pull_request:
    types: [closed, unlabeled]
  workflow_dispatch:
    inputs:
      pr_number:
        description: PR number of review app to delete
        required: true
        type: string

jobs:
  delete-review-app:
    name: Delete review app
    runs-on: ubuntu-latest
    concurrency: delete-review-app-${{ github.event.pull_request.number || github.event.inputs.pr_number }}
    if: >
      github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'deploy') ||
      (github.event.action == 'unlabeled' && github.event.label.name == 'deploy') || (github.event_name ==
      'workflow_dispatch')
    permissions:
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Delete review app
        uses: DFE-Digital/github-actions/delete-review-app@master
        with:
          pr-number: ${{ github.event.pull_request.number || github.event.inputs.pr_number }}
          resource-group-name: "s189t01-catp-rg"
          storage-account-name: "s189t01catptfstate"
          tf-state-file: "catp.tfstate"
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
