name: Delete Review App

on:
  pull_request:
    types: [closed]

jobs:
  delete-review-app:
    name: Delete Review App ${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: 'https://dev.azure.com/dfe-ssp/S118-Teacher-Payments-Service'
          azure-pipeline-name: 'DFE-Digital.claim-additional-payments-for-teaching-destroy-review-app' # name of the Azure pipeline to be triggered
          azure-devops-token: '${{ secrets.AZUREDEVOPSTOKEN }}'
          azure-pipeline-variables: '{"pr_number": "${{ github.event.pull_request.number }}"}'

    name: Delete tf state file
    if: env.TF_STATE_EXISTS == 'true'
    run: |
         az storage blob delete -c review-app-tfstate --name ${{ env.TF_STATE_FILE }} \
         --connection-string $AZURE_STORAGE_CONNECTION_STRING
    env:
    AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING_REVIEW }}
