name: Notify Analytics Config Changes

on:
  push:
    branches:
      - master
    paths:
      - 'config/analytics_hidden_pii.yml'
      - 'config/analytics_blocklist.yml'
      - 'config/analytics.yml'
      - 'config/analytics_pii.yml'
  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch remote master for comparison
        run: git fetch origin master --depth=2

      - name: Get analytics config changes
        id: analytics-diff
        run: |
          echo "ANALYTICS_DIFF<<EOF" >> $GITHUB_ENV
          git diff origin/master^..origin/master -- config/analytics_hidden_pii.yml config/analytics_blocklist.yml config/analytics.yml config/analytics_pii.yml >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Get commit details
        id: commit-info
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%s | sed 's/"//g')
          COMMIT_AUTHOR=$(git log -1 --pretty=%an | sed 's/"//g')
          COMMIT_LINK="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV
          echo "COMMIT_LINK=$COMMIT_LINK" >> $GITHUB_ENV

      - name: Notify Slack
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "${{ format(
                '<@U033AJ0A12P> Analytics Configuration Change Detected 🔍\n\n*Commit:* <{0}|{1}>\n\n*Author:* {2}\n\n*Branch:* {3}\n\n*Analytics Config Changes:*\n```diff\n{4}\n```',
                env.COMMIT_LINK,
                env.COMMIT_MSG,
                env.COMMIT_AUTHOR,
                github.ref_name,
                env.ANALYTICS_DIFF
              ) }}"
            }
